---
name: hazel

instance_groups:

- name: docker
  azs: [z1,z2,z3]
  instances: 3
  persistent_disk: 65536
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: docker
    release: hazel
    properties:
      tcp_address: 0.0.0.0
      tls_cacert: "((docker-tls.ca))"
      tls_cert: "((docker-tls.certificate))"
      tls_key: "((docker-tls.private_key))"
  - name: containers
    release: hazel
    provides:
      hazelpeers: {shared: true}
    consumes:
      peers: {from: peers, deployment: zoo }
    properties:
      containers:
        - name: hazelcast1
          image: "fab-ci-remote-agent:443/hazelcast1"
          memory: "512m"
          env_vars:
            - "EXAMPLE_VAR=1"

variables:
- name: docker-ca
  type: certificate
  options:
    is_ca: true
    common_name: dockerCA
- name: docker-tls
  type: certificate
  options:
    ca: docker-ca
    common_name: docker
    extended_key_usage:
    - client_auth

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 32
  serial: false

releases:
- name: hazel
  version: 0+dev.41
